[project]
name = "fibonacci-tdd-kata-viethung103"
version = "0.1.0"
description = "A TDD Kata: Fibonacci, from notebook exploration to a tested, pubilshed package"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "viethung", email = "viethungpc103@gmail.com"}]

[project.scripts]
fibonacci-tdd-kata = "fibonacci_tdd_kata:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "marimo>=0.10",
    "pytest>=8.0",
    "ruff>=0.6",
    "pytest-cov>=5.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff]
extend-exclude = ["notebooks"]
